@startuml 1.puml

left to right direction
skinparam Nodesep 5

f19 0--0 b10 :""1--0""
f13--0 b15 :""--0""
f12--@ b12 : ""--@""


f11 --:|> b11:""-->""
f4--o b4:""1--o""
f3 --* b3: ""1--n""



@enduml